### ISSUE TITLE
对于时序类的异常检测有相关代码吗？

### ISSUE THREAD

**Issue by xljhtq** [RexKing6/blog.rexking6.github.io#1]
博主：
      你好，看你罗列了很多时序类的异常检测，你有尝试过相关的代码吗？有比较好用的，可否将代码分享一下？
                                                                                                                                     谢谢！

**Comment by RexKing6** [comment]
时序类的异常检测，目前基本分为两种：
1. 动态阈值，无需训练，通过预测模型的预测值和真实值之间的误差，超过动态的特定阈值，即算为异常；这种效果比较一般，但是不用训练过程（是指已经存在预测模型），这种我试了NASA的Detecting Spacecraf Anomalies Using LSTMs and Nonparametric Dynamic Thresholding，里面也有代码，你可以试试；
2. 第二种就是划分时间窗口后，按照机器学习中经典的异常检测算法来处理，常见的有我列举的那些，比如单类SVM之类，最近用的是裴丹的Unsupervised Anomaly Detection via Variational Auto-Encoder for Seasonal KPIs in Web Applications，里面对VAE做了改进，也是有代码的，这种效果就会比第一种好很多，但是每条序列都需要训练，实际环境中如果数据量过大，可能就不太适用了，你也可以试试。




------------------ 原始邮件 ------------------
发件人: "xljhtq"<notifications@github.com>;
发送时间: 2019年5月8日(星期三) 中午12:05
收件人: "RexKing6/blog.rexking6.github.io"<blog.rexking6.github.io@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>; 
主题: [RexKing6/blog.rexking6.github.io] 对于时序类的异常检测有相关代码吗？ (#1)




博主：
 你好，看你罗列了很多时序类的异常检测，你有尝试过相关的代码吗？有比较好用的，可否将代码分享一下？
 谢谢！

**Comment by xljhtq** [comment]
@RexKing6 第二种方法是用时序数据抽取一些特征，转成非时序类的异常检测去做，是吗？
1. 对于特征抽取，包括抽取时序的ss,ls,chain,ca等是吗？一般还有哪些特征可以抽取
2.对于非时序的异常检测算法，一般哪个效果比较好，可以轻量级的，不要像深度网络那块那么重？

**Comment by RexKing6** [comment]
对的，像裴丹的方法我们直接提取窗口作为特征，相比于普通的异常检测方法+多种提取特征（方差，EMWA之类的）的手段会好很多。




------------------ 原始邮件 ------------------
发件人: "xljhtq"<notifications@github.com>;
发送时间: 2019年5月8日(星期三) 下午2:40
收件人: "RexKing6/blog.rexking6.github.io"<blog.rexking6.github.io@noreply.github.com>;
抄送: "陈润青"<1010026261@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [RexKing6/blog.rexking6.github.io] 对于时序类的异常检测有相关代码吗？ (#1)




@RexKing6 第二种方法是用时序数据抽取一些特征，转成非时序类的异常检测去做，是吗？
  
对于特征抽取，包括抽取时序的ss,ls,chain,ca等是吗？一般还有哪些特征可以抽取
 2.对于非时序的异常检测算法，一般哪个效果比较好，可以轻量级的，不要像深度网络那块那么重？

**Comment by RexKing6** [comment]
1. 抽取时序的特征有很多种方法，具体可以参考去年裴丹举办的一个比赛，其中有前五名的ppt，说明了怎么提取特征？
2. 普通的异常检测方法有很多，资料也很多，你可以找找，具体效果我们试了单类SVM，都不如裴丹的，而且裴丹这个方法，其实也没多深，encoder+decoder也就4层，不算是深度。




------------------ 原始邮件 ------------------
发件人: "xljhtq"<notifications@github.com>;
发送时间: 2019年5月8日(星期三) 下午2:40
收件人: "RexKing6/blog.rexking6.github.io"<blog.rexking6.github.io@noreply.github.com>;
抄送: "陈润青"<1010026261@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [RexKing6/blog.rexking6.github.io] 对于时序类的异常检测有相关代码吗？ (#1)




@RexKing6 第二种方法是用时序数据抽取一些特征，转成非时序类的异常检测去做，是吗？
  
对于特征抽取，包括抽取时序的ss,ls,chain,ca等是吗？一般还有哪些特征可以抽取
 2.对于非时序的异常检测算法，一般哪个效果比较好，可以轻量级的，不要像深度网络那块那么重？

**Comment by RexKing6** [comment]
http://iops.ai/competition_detail/?competition_id=5&flag=1
https://github.com/chenryn/aiops-handbook
https://github.com/linjinjin123/awesome-AIOps
几个可能有用的url，你可以看一下。




------------------ 原始邮件 ------------------
发件人: "xljhtq"<notifications@github.com>;
发送时间: 2019年5月8日(星期三) 下午2:40
收件人: "RexKing6/blog.rexking6.github.io"<blog.rexking6.github.io@noreply.github.com>;
抄送: "陈润青"<1010026261@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [RexKing6/blog.rexking6.github.io] 对于时序类的异常检测有相关代码吗？ (#1)




@RexKing6 第二种方法是用时序数据抽取一些特征，转成非时序类的异常检测去做，是吗？
  
对于特征抽取，包括抽取时序的ss,ls,chain,ca等是吗？一般还有哪些特征可以抽取
 2.对于非时序的异常检测算法，一般哪个效果比较好，可以轻量级的，不要像深度网络那块那么重？

**Comment by xljhtq** [comment]
@RexKing6 
1. 对于vae这种方法，之前用过。但是目前有点疑问：这种模型应该是针对的具有周期性数据而言才起作用的吧？如果数据是短期的，并不一定是周期性的，可能数据出现“尖峰”、“冲高”、“突然下跌“等这种现象，你们是否试过vae或其他方法的有效性？
2. 对于vae这种模型，应该预测延迟单核是超过100ms的吧？这样其实性能上应该是不高的

**Comment by RexKing6** [comment]
1. 我这边一些非周期性但是是长期的数据，vae是有效的；而且原理上我觉得好像和周期性没有太大关系，像你说的“尖峰”“冲高”突然下跌“都能够具体地表现在窗口特征中具体的某几维，这样在特征空间中就会有比较大的偏离。如果数据实在很短的话，我觉得可以试试数据增强，相关的文章貌似有用GAN做的，如果效果还是不好的话，我觉得直接 3-sigma 或者我前面说的动态阈值也是能有效果的。
2. 按你说的，性能确实是不高的；不过我这边实际场景中要求实时的时间粒度是分钟和小时，也够用了。如果你的时间粒度要求比较高的话，我前面说的动态阈值的方法就不用考虑了，它的预测延迟也会比较高。而且普通的异常检测方法，一般集成的效果会比较好，估计预测速度也会比较慢，最普通的可以试试3-sigma，实话说，效果还行，我这里用作基线。




------------------ 原始邮件 ------------------
发件人: "xljhtq"<notifications@github.com>;
发送时间: 2019年5月8日(星期三) 下午3:58
收件人: "RexKing6/blog.rexking6.github.io"<blog.rexking6.github.io@noreply.github.com>;
抄送: "陈润青"<1010026261@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [RexKing6/blog.rexking6.github.io] 对于时序类的异常检测有相关代码吗？ (#1)




@RexKing6
  
对于vae这种方法，之前用过。但是目前有点疑问：这种模型应该是针对的具有周期性数据而言才起作用的吧？如果数据是短期的，并不一定是周期性的，可能数据出现“尖峰”、“冲高”、“突然下跌“等这种现象，你们是否试过vae或其他方法的有效性？
 
对于vae这种模型，应该预测延迟单核是超过100ms的吧？这样其实性能上应该是不高的
